=== thrace-app/addresses/schema/account.schema.json
{
  "$id": "https://github.com/thrace-app/addresses/schema/account.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Account",
  "type": "object",
  "properties": {
    "address": {
      "type": "string"
    },
    "displayName": {
      "type": "string"
    },
    "group": {
      "type": "string"
    },
    "type": {
      "type": "string",
      "enum": [
        "WALLET",
        "TOKEN",
        "EXCHANGE",
        "SWAP",
        "BRIDGE",
        "MARKETPLACE",
        "LIQUIDITY_PROVIDER",
        "MIXER",
        "OTHER"
      ]
    },
    "token": {
      "$ref": "./token.schema.json"
    }
  },
  "required": ["address", "displayName", "type"],
  "anyOf": [
    {
      "properties": {
        "type": { "const": "TOKEN" }
      },
      "required": ["token"]
    }
  ]
}

=== thrace-app/addresses/networks/1/assets/0x2bfa4/0x2bfa4843f5945b59f072238cafae2d0737131118/info.json
{
  "$schema": "../../../../schema/account.schema.json",
  "address": "0x2bfa4843f5945b59f072238cafae2d0737131118",
  "displayName": "Baby Lonely Alien Space Club",
  "type": "TOKEN",
  "token": {
    "name": "Baby Lonely Alien Space Club",
    "symbol": "BLASC",
    "decimals": 18,
    "type": "ERC20"
  }
}

=== thrace-app/addresses/networks/1/assets/0x66a60/0x66a60d14c73dccd1626a909559a83525612700bc/info.json
{
  "$schema": "../../../../schema/account.schema.json",
  "address": "0x66a60d14c73dccd1626a909559a83525612700bc",
  "displayName": "Beneficent Governance Token",
  "type": "TOKEN",
  "token": {
    "name": "Beneficent Governance Token",
    "symbol": "BGT",
    "decimals": 18,
    "type": "ERC20"
  }
}

=== thrace-app/addresses/networks/1/assets/0x81af9/0x81af96818a8aeaca466a898ebf7dfe5741da95c0/info.json
{
  "$schema": "../../../../schema/account.schema.json",
  "address": "0x81af96818a8aeaca466a898ebf7dfe5741da95c0",
  "displayName": "Domino Harvey Bounty Hunter",
  "type": "TOKEN",
  "token": {
    "name": "Domino Harvey Bounty Hunter",
    "symbol": "DHBH",
    "decimals": 9,
    "type": "ERC20"
  }
}

=== thrace-app/addresses/networks/1/assets/0x1748d/0x1748dc7c79745fc34251a905ec99e4b6bc8a2203/info.json
{
  "$schema": "../../../../schema/account.schema.json",
  "address": "0x1748dc7c79745fc34251a905ec99e4b6bc8a2203",
  "displayName": "Terra Classic USD (Wormhole)",
  "type": "TOKEN",
  "token": {
    "name": "Terra Classic USD (Wormhole)",
    "symbol": "USTC",
    "decimals": 18,
    "type": "ERC20"
  }
}

=== thrace-app/addresses/networks/1/assets/0xea5ed/0xea5edef1c6ed1be1bcba4617a1c5a994e9018a43/info.json
{
  "$schema": "../../../../schema/account.schema.json",
  "address": "0xea5edef1c6ed1be1bcba4617a1c5a994e9018a43",
  "displayName": "cvxsteCRV Ease Vault",
  "type": "TOKEN",
  "token": {
    "name": "cvxsteCRV Ease Vault",
    "symbol": "ez-cvxsteCRV",
    "decimals": 18,
    "type": "ERC20"
  }
}

=== thrace-app/addresses/networks/1/assets/0x2d0db/0x2d0db905bc6e587e6f37260b946d32d302028901/info.json
{
  "$schema": "../../../../schema/account.schema.json",
  "address": "0x2d0db905bc6e587e6f37260b946d32d302028901",
  "displayName": "MillionTech | t.me/MillionTech",
  "type": "TOKEN",
  "token": {
    "name": "MillionTech | t.me/MillionTech",
    "symbol": "MT",
    "decimals": 18,
    "type": "ERC20"
  }
}
